### ISSUE TITLE
docs: Releases new keyword filters

### ISSUE THREAD

**Issue by zze0s** [autobrr/autobrr.com#51]
Document https://github.com/autobrr/autobrr/pull/564

**Comment by s0up4200** [comment]
Will PR this once its out of develop I guess. https://github.com/autobrr/autobrr.com/commit/77ce1168a7d6bfc8542fff87f1fd563cce2c012c

**Comment by s0up4200** [comment]
Merged in https://github.com/autobrr/autobrr.com/pull/53
